# Generated by Django 6.0.1 on 2026-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop_name', models.CharField(max_length=100)),
                ('delivery_days', models.IntegerField(default=0)),
                ('url', models.URLField()),
            ],
        ),
    ]
