# Generated by Django 6.0.1 on 2026-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Kuriér na adresu (+4.90 € / balík)'), ('box', 'Výdajné miesto / Box (+2.90 € / balík)')], default='courier', max_length=20),
        ),
    ]
