# Generated by Django 6.0.1 on 2026-01-31 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 31, 20, 23, 19, 33897, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
