# Generated by Django 6.0.1 on 2026-01-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='external_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_oversized',
            field=models.BooleanField(default=False, verbose_name='Nadrozmerný tovar (len kuriér)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='delivery_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offer',
            name='url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Kuriér na adresu (+4.90 €)'), ('box', 'Výdajné miesto / Box (+2.90 €)')], default='courier', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('shop_name', 'external_item_id')},
        ),
    ]
