# Generated by Django 6.0.1 on 2026-02-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_offer_is_sponsored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_category_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cena od'),
        ),
    ]
