# Generated by Django 6.0.1 on 2026-01-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_order_options_alter_cartitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nova', 'Nová / Prijatá'), ('spracovava_sa', 'Spracováva sa'), ('odoslana', 'Odoslaná'), ('dorucena', 'Doručená'), ('zrusena', 'Zrušená')], default='nova', max_length=20),
        ),
    ]
