# Generated by Django 6.0.1 on 2026-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_is_active_productparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_category_text',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
