# Generated by Django 6.0.1 on 2026-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_is_active_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_category_locked',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Kategória uzamknutá (AI)'),
        ),
    ]
