# Generated by Django 6.0.1 on 2026-02-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_is_category_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_confidence',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
